## 单层神经网络

### 回归神经网络：线性回归

In [1]:
import numpy as np

In [2]:
X = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
z_reg = np.array([-0.2, -0.05, -0.05, 0.1])

In [3]:
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [4]:
X.shape

(4, 2)

In [5]:
z_reg

array([-0.2 , -0.05, -0.05,  0.1 ])

In [6]:
# 定义实现简单线性回归的函数
def LinearR(x1, x2):
    w1, w2, b = 0.15, 0.15, -0.2  # 给定一组系数w和b
    z = x1*w1 + x2*w2 + b  # z是系数*特征后加和的结果
    return z

In [7]:
LinearR(X[:, 0], X[:, 1])

array([-0.2 , -0.05, -0.05,  0.1 ])

### 二分类单层神经网络：sigmoid与阶跃函数

In [8]:
# 重新定义数据中的标签
y_and = [0, 0, 0, 1]

In [9]:
# 根据sigmoid公式定义sigmoid函数
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [10]:
def AND_sigmoid(x1, x2):
    w1, w2, b = 0.15, 0.15, -0.2  # 给定的系数w和b不变
    z = x1*w1 + x2*w2 + b
    o = sigmoid(z)  # 使用sigmoid函数将回归结果转换到(0,1)之间
    y = (o >= 0.5).astype(int)
#     y = [int(x) for x in o >= 0.5] #根据阈值0.5，将(0,1)之间的概率转变为分类0和1
    return o, y

In [11]:
# o:sigmoid函数返回的概率结果
# y:对概率结果按阈值进行划分后，形成的0和1，也就是分类标签
o, y_sigm = AND_sigmoid(X[:, 0], X[:, 1])

In [12]:
o

array([0.450166  , 0.4875026 , 0.4875026 , 0.52497919])

In [13]:
y_sigm

array([0, 0, 0, 1])

In [14]:
y_sigm == y_and?

In [ ]:
y_sigm == y_and

In [15]:
y_sigm == y_and

array([ True,  True,  True,  True])

In [19]:
# 阶跃函数
def AND(x1, x2):
    w1, w2, b = 0.15, 0.15, -0.23  # 和sigmoid相似的w和b
    z = x1*w1 + x2*w2 + b
    y = (z >= 0).astype(int)
#     y = [int(x) for x in z >= 0]
    return y

In [20]:
AND(X[:, 0], X[:, 1])

array([0, 0, 0, 1])

### 多分类单层神经网络：softmax回归

In [22]:
z = np.array([1010, 1000, 990])
np.exp(z) / np.sum(np.exp(z))   # softmax函数的运算

<ipython-input-22-ed38db1fa6f8>:2: RuntimeWarning: overflow encountered in exp
  np.exp(z) / np.sum(np.exp(z))
<ipython-input-22-ed38db1fa6f8>:2: RuntimeWarning: invalid value encountered in true_divide
  np.exp(z) / np.sum(np.exp(z))


array([nan, nan, nan])

In [23]:
# 定义softmax函数
def softmax(z):
    c = np.max(z)
    exp_z = np.exp(z - c)  # 溢出对策
    sum_exp_z = np.sum(exp_z)
    o = exp_z / sum_exp_z
    return o

In [24]:
softmax(z)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [25]:
sum(softmax(z))

1.0