## MinMaxScaler

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
# 不太熟悉numpy的小伙伴，能够判断data的结构吗？
# 如果换成表是什么样子？
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [2]:
# 实现归一化
scaler = MinMaxScaler()  # 实例化
scaler = scaler.fit(data)  # fit，在这里本质是生成min(x)和max(x)
result = scaler.transform(data)  # 通过接口导出结果
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [3]:
result_ = scaler.fit_transform(data)  # 训练和导出结果一步达成
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [4]:
scaler.inverse_transform(result)  # 将归一化后的结果逆转

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [5]:
import numpy as np
X = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])

# 归一化
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [6]:
# 逆归一化
X_returned = X_nor * (X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)
X_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

## StandardScaler

In [7]:
from sklearn.preprocessing import StandardScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

scaler = StandardScaler()  # 实例化
scaler.fit(data)  # fit，本质是生成均值和方差

scaler.mean_  # 查看均值的属性mean_
scaler.var_  # 查看方差的属性var_

x_std = scaler.transform(data)  # 通过接口导出结果

x_std.mean()  # 导出的结果是一个数组，用mean()查看均值
x_std.std()  # 用std()查看方差

scaler.fit_transform(data)  # 使用fit_transform(data)一步达成结果

scaler.inverse_transform(x_std)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

## 处理缺失值

In [8]:
import pandas as pd
data = pd.read_csv('./data/Narrativedata.csv', index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [10]:
Age = data.loc[:, "Age"].values.reshape(-1, 1)  # sklearn当中特征矩阵必须是二维
Age[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [nan],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [nan],
       [31.],
       [nan]])

In [11]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer()  # 实例化，默认均值填补
imp_median = SimpleImputer(strategy="median")  # 用中位数填补
imp_0 = SimpleImputer(strategy="constant", fill_value=0)  # 用0填补
imp_mean = imp_mean.fit_transform(Age)  # fit_transform一步完成调取结果
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

imp_mean[:20]
imp_median[:20]
imp_0[:20]

# 在这里我们使用中位数填补Age
data.loc[:, "Age"] = imp_median

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [12]:
# 使用众数填补Embarked
Embarked = data.loc[:, "Embarked"].values.reshape(-1, 1)
imp_mode = SimpleImputer(strategy="most_frequent")
data.loc[:, "Embarked"] = imp_mode.fit_transform(Embarked)

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [13]:
import pandas as pd
# index_col=0将第0列作为索引，不写则认为第0列为特征
data_ = pd.read_csv('./data/Narrativedata.csv', index_col=0)

data_.head()

data_.loc[:, "Age"] = data_.loc[:, "Age"].fillna(data_.loc[:, "Age"].median())
# .fillna 在DataFrame里面直接进行填补

data_.dropna(axis=0, inplace=True)
# .dropna(axis=0)删除所有有缺失值的行，.dropna(axis=1)删除所有有缺失值的列
# 参数inplace，为True表示在原数据集上进行修改，为False表示生成一个复制对象，不修改原数据，默认False
# _data_ = data_.drop(axis=0,inplace=False)

## 处理分类型特征：编码与哑变量

### LabelEncoder

In [14]:
from sklearn.preprocessing import LabelEncoder

y = data_.iloc[:, -1]  # 要输入的是标签，不是特征矩阵，所以允许一维

le = LabelEncoder()  # 实例化
le = le.fit(y)  # 导入数据
label = le.transform(y)  # transform接口调取结果

le.classes_  # 属性.classes_查看标签中究竟有多少类别
label  # 查看获取的结果label

le.fit_transform(y)  # 也可以直接fit_transform一步到位

le.inverse_transform(label)  # 使用inverse_transform可以逆转

array(['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'Unknown', 'Yes', 'No', 'No', 'No', 'Unknown', 'No', 'Yes', 'No',
       'Yes', 'Unknown', 'Yes', 'Yes', 'Yes', 'No', 'Unknown', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Unknown', 'Yes', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'Unknown', 'No', 'Unknown',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Unknown', 'Yes',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'Unknown', 'No', 'No', 'Yes', 'No', 'No', 'Ye

### OrdinalEncoder

In [15]:
from sklearn.preprocessing import OrdinalEncoder
# 接口categories_对应LabelEncoder的接口classes_，一模一样的功能
data_ = data.copy()

data_.head()

OrdinalEncoder().fit(data_.iloc[:, 1: -1]).categories_
data_.iloc[:, 1: -1] = OrdinalEncoder().fit_transform(data_.iloc[:, 1: -1])
data_.head()

Age  Sex  Embarked Survived
0  22.0  1.0       2.0       No
1  38.0  0.0       0.0      Yes
2  26.0  0.0       2.0      Yes
3  35.0  0.0       2.0      Yes
4  35.0  1.0       2.0       No

### OneHotEncoder

In [16]:
from sklearn.preprocessing import OneHotEncoder
X = data.iloc[:, 1: -1]
enc = OneHotEncoder(categories='auto').fit(X)
result = enc.transform(X).toarray()
result

# 依然可以直接一步到位，但为了给大家展示模型属性，所以还是写成了三步
OneHotEncoder(categories='auto').fit_transform(X).toarray()

# 依然可以还原
pd.DataFrame(enc.inverse_transform(result))

enc.get_feature_names()  # 返回每一个经过哑变量后生成稀疏矩阵列的名字

result.shape
# axis=1,表示跨行进行合并，也就是将两表左右相连，如果是axis=0，就是将量表上下相连
newdata = pd.concat([data, pd.DataFrame(result)], axis=1)
newdata.head()
newdata.drop(["Sex", "Embarked"], axis=1, inplace=True)

newdata.columns = ["Age", "Survived", "Female",
                   "Male", "Embarked_C", "Embarked_Q", "Embarked_S"]

newdata.head()

Age Survived  Female  Male  Embarked_C  Embarked_Q  Embarked_S
0  22.0       No     0.0   1.0         0.0         0.0         1.0
1  38.0      Yes     1.0   0.0         1.0         0.0         0.0
2  26.0      Yes     1.0   0.0         0.0         0.0         1.0
3  35.0      Yes     1.0   0.0         0.0         0.0         1.0
4  35.0       No     0.0   1.0         0.0         0.0         1.0

## 处理连续型特征：二值化与分段

### Binarizer

In [17]:
# 将年龄二值化

from sklearn.preprocessing import Binarizer
data_2 = data.copy()
X = data_2.iloc[:, 0].values.reshape(-1, 1)  # 类为特征专用，所以不能使用一维数组
transformer = Binarizer(threshold=30).fit_transform(X)
data_2.iloc[:, 0] = transformer
data_2.head()

Age     Sex Embarked Survived
0  0.0    male        S       No
1  1.0  female        C      Yes
2  0.0  female        S      Yes
3  1.0  female        S      Yes
4  1.0    male        S       No

In [19]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
transformer = Binarizer(threshold=[2, 1, 1]).fit(X)  # fit does nothing.
transformer

transformer.transform(X)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

### KBinsDiscretizer

In [22]:
from sklearn.preprocessing import KBinsDiscretizer
X = data.iloc[:, 0].values.reshape(-1, 1)
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
est.fit_transform(X)

# 查看转换后分的箱：变成了一列中的三箱
set(est.fit_transform(X).ravel())

{0.0, 1.0, 2.0}

In [23]:
est = KBinsDiscretizer(n_bins=3, encode='onehot', strategy='uniform')
# 查看转换后分的箱：变成了哑变量
est.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])